server:
  port: 8202
spring:  
  profiles:  
    active: dev   
application:
    name: microservicecloud-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/ 
---  
# 测试环境配置  
server:
  port: 8201
spring:  
  profiles: test  
application:
    name: microservicecloud-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/ 
